version: "3.4"

services:
  sso:
    build:
      context: ../
      network: host
      dockerfile: ./docker/Dockerfile
    image: 103.14.34.141:5000/sanmingzi/sso:1.0.0
    container_name: sso
    network_mode: "host"
    command: /bin/sh -c "top -b"
